### PR TITLE
bump: pgvecto.rs v0.2.0

### PR DESCRIPTION
**Pull request by bo0tzz**
Sidenote: I used to have these updates automated using [renovate](https://docs.renovatebot.com/). Is that something we want to enable on this repository as well?

### CODE REVIEW

**Comment by gaocegege** [comment]
@bo0tzz Let' enbale it. It seems to be a self hosted GitHub app, should we enable your app on the repository?

**Comment by bo0tzz** [comment]
Renovate has a managed github app, that's the easiest way to set it up. https://docs.renovatebot.com/getting-started/installing-onboarding/#hosted-githubcom-app

Once it's enabled for this repository, it should automatically pick up the existing config file and start working. If we leave this PR open it should create its own pr for this 0.2.0 version bump, which would be a nice test run.

**Comment by gaocegege** [comment]
Thanks for your guide, I enabled it.

**Comment by bo0tzz** [comment]
Closed in favour of #3

**Comment by gaocegege** [comment]
Thank you for your contribution!

**Pull request closed without merging**
